### ISSUE TITLE
签到问题

### ISSUE THREAD

**Issue by simplein** [shuye73/MyActions#11]
今天让程序运行了一天，然后app上检查一下还有没有没签到的。发现“智能生活”和“X东定制”似乎没签到过，有豆子领。不知道是我的问题，还是代码里面没加这两个签到。麻烦大佬看看。

**Comment by shuye73** [comment]
目前不太清楚，签到脚本是另一个大佬写的 ，我搬运的。有更新我随时就同步更新了
