### ISSUE TITLE
自动同步问题

### ISSUE THREAD

**Issue by jatalin** [shuye73/MyActions#12]
自动同步脚本有点问题吧，现在1小时更新好多次，不会弄炸了吗？

**Comment by shuye73** [comment]
好多次嘛？我看一下，昨天为了推文件到gitee测试docker了所以可能调了一下 ，现在调回来了

**Comment by jatalin** [comment]
> 好多次嘛？我看一下，昨天为了推文件到gitee测试docker了所以可能调了一下 ，现在调回来了
