### ISSUE TITLE
麻烦修改下docker镜像的hosts文件

### ISSUE THREAD

**Issue by kanvenzeng** [shuye73/MyActions#18]
老大好，可以修改下yarn源的ipv6解析吗？ipv6小鸡运行git_pull.sh连接不了

2606:4700::6810:1723 registry.yarnpkg.com
2606:4700::6810:1723 registry.npmjs.org
2606:4700::6810:ab63 yarnpkg.com

**Comment by shuye73** [comment]
好的 有空看一下

**Comment by kanvenzeng** [comment]
ok
