### ISSUE TITLE
大佬，多个任务出错。

### ISSUE THREAD

**Issue by dong0623** [shuye73/MyActions#19]
京东排行榜，京东赚赚小程序，京东首页领京东豆，京东宠旺旺偷好友狗粮和积分，京东进店领豆等。。。
reference is not a tree: 253ac23a29a7c7d285fa8a5893762e5f98540741
build: .github#L1
Git checkout failed with exit code: 128
build: .github#L1
Exit code 1 returned from process: file name '/home/runner/runners/2.277.1/bin/Runner.PluginHost', arguments 'action "GitHub.Runner.Plugins.Repository.v1_0.CheckoutTask, Runner.Plugins"'.
build: .github#L1
Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see https://github.com/actions/virtual-environments/issues/1816
京东排行榜: .github#L1
类似这样的报错。

**Comment by shuye73** [comment]
在搞美丽研究院，现在已经改回来了
