### ISSUE TITLE
不知道你拉脚本改助力码是什么心态呢？

### ISSUE THREAD

**Issue by i-chenzhe** [shuye73/MyActions#21]

**Comment by solodarker** [comment]
不是吧，这也能喷，我为人人，人人为我，你自己去提交助力码池也有人助力你啊，自己不去提交怪谁呢。

**Comment by hkxiaopang** [comment]
> 不是吧，这也能喷，我为人人，人人为我，你自己去提交助力码池也有人助力你啊，自己不去提交怪谁呢。

大佬，助力池在哪里呀
