### ISSUE TITLE
昨天听到某个传闻把库私有化了，今天action就爆仓了

### ISSUE THREAD

**Issue by sweetasaki** [shuye73/MyActions#25]
问了下朋友，没私有化的都没问题，私有化的都炸了。是不是私有化会占用action资源？公开的不用

**Comment by shuye73** [comment]
私有化之后 action功能变为收费功能，有使用时限。github只对私有收费 公开的免费使用

**Comment by hacken156026692** [comment]
咨询一下大佬几个小问题：
1、我按照您的教程，同步了，并把仓库设置了private，请问，private的话，action还会不会造成cookie泄漏风险？
2、您的声明里，这个评论，是哪里的聊天记录？微博里没搜到。我加了您的电报群，但只有您定期更新发布的，想问问，有没有类似声明里的这种互动聊天的平台或群。
3、我是安卓系统，目前主要是用手机termux里运行京东的程序、action是辅助运行。您的脚本好像只能action和docker的是吧？
4、目前action都是红色的x，是不是action接下来不能用了？

谢谢您为大家的付出！

**Comment by qilin7** [comment]
private的ac有时长限制，跑个joy挂机直接24小时的跑，肯定炸了

**Comment by hacken156026692** [comment]
> private的ac有时长限制，跑个joy挂机直接24小时的跑，肯定炸了

好的，明白了。怪不得。

**Comment by shuye73** [comment]
private之后有额度限制，挂机是24小时一直跑但是由于action限制最多运行6小时，所以挂机一天分四次运行，但是还是会把你的额度跑光，目前在筹备云函数，希望大家慢慢转战云函数吧安全一点

**Comment by shuye73** [comment]
action红色的叉要么你额度跑光了 要么你的号被ban了，如果想继续跑 建议换号

**Comment by hacken156026692** [comment]
> action红色的叉要么你额度跑光了 要么你的号被ban了，如果想继续跑 建议换号

明白了。我现在一直是用原来evinedeng部署的安卓平台，您这个脚本好像用不了，后续云函数的话，能涵盖安卓平台吗？docker用不了。-_-||

**Comment by davewang1988** [comment]
私有化过直接炸了，换了个名字按照教程又开始跑起来了，好像时间2000分钟的样子。

**Comment by shuye73** [comment]
云函数涵盖安卓平台？我没听懂

**Comment by hacken156026692** [comment]
> 云函数涵盖安卓平台？我没听懂

我意思是，我现在用的安卓，用termux跑的脚本，之前按Evinedeng那个教程跑的脚本，手机上直接跑，很方便。后来他404消失了，我试过其他几个脚本，大部分只支持在Boxjs、QuanX和docker里运行。我运行您的脚本，可能是我没设置对、或者你这脚本确实不支持手机里直接运行，所以才问一下，新推出的云函数是否涵盖termux等安卓本地运行平台。

谢谢！

**Comment by aixiaolu** [comment]
> 云函数涵盖安卓平台？我没听懂

大佬，云函数能同步更新吗，希望教程详细点，之前的云函数苦于更新和运行900s限制一直用的ac，谢谢了

**Comment by shuye73** [comment]
云函数能同步更新，教程尽量吧。云函数没有我想象中的那么好用
