### ISSUE TITLE
看见个自动删除ac历史的库

### ISSUE THREAD

**Issue by qilin7** [shuye73/MyActions#26]
[自动删除ac历史](https://github.com/Mattraks/delete-workflow-runs)，大佬有兴趣可以看下，加不加感觉也没啥必要。。。。

**Comment by shuye73** [comment]
感谢分享，后续如有需要就加入，目前在筹备云函数

**Comment by yao32** [comment]
> 感谢分享，后续如有需要就加入，目前在筹备云函数

大佬，我的tg:@Allen2033,能找你聊天么？不知道早上那位是不是！哈哈😄
