### ISSUE TITLE
大佬只玩京东吗

### ISSUE THREAD

**Issue by davewang1988** [shuye73/MyActions#27]
大佬是否准备考虑出点视频软件的，这样每天自动点点任务爽歪歪。

**Comment by hacken156026692** [comment]
兄弟，看样子是老司机了，方便加Q吗？

**Comment by hacken156026692** [comment]
> 大佬是否准备考虑出点视频软件的，这样每天自动点点任务爽歪歪。

兄弟，看样子是老司机了，方便加Q吗？

**Comment by shuye73** [comment]
收益太低  提现门槛过高 黑号风险过大 吃力不讨好 还是去找tg群 自己拿QX跑吧 目前不怎么想搬运那些
