### ISSUE TITLE
京东秒秒币

### ISSUE THREAD

**Issue by gwl410716154** [shuye73/MyActions#30]
大佬早上好，京东秒秒币脚本（jd_ms.js）AC执行成功，但实际上没有拿到秒秒币，用电脑手动执行却正常拿到秒秒币，望有空看看，谢谢

正常情况下执行是有提示，
�京东秒秒币, 开始!

====================共有n个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021-2-25 8:43:58===============
===

******开始【京东账号】********

活动名称：秒杀红包二期正式
当前秒秒币XX
去做浏览秒杀优选店铺任务：1/2
任务领取成功
任务完成
去做浏览秒杀优选店铺任务：2/2
任务领取成功
任务完成
去做浏览秒杀超值好物任务：1/2

============================

但在AC上执行没有以上结果内容

**Comment by shuye73** [comment]
看了 并没有发现什么问题  日志正常任务也做 如果更多人反馈 我再查查原因吧

**Comment by gwl410716154** [comment]
好的，谢谢大佬
