### ISSUE TITLE
试用jd_try脚本不申请问题

### ISSUE THREAD

**Issue by lance56** [shuye73/MyActions#31]
试用脚本不申请试用，请问大佬是怎么回事？

`开始【京东账号1】#########

⏰ 获取 家用电器 普通试用 商品列表
⏰ 获取 家用电器 闪电试用 商品列表
⏰ 获取 手机数码 普通试用 商品列表
⏰ 获取 手机数码 闪电试用 商品列表
⏰ 获取 电脑办公 普通试用 商品列表
⏰ 获取 电脑办公 闪电试用 商品列表
⏰ 获取 家居家装 普通试用 商品列表
⏰ 获取 家居家装 闪电试用 商品列表
⏰ 过滤商品列表，当前共有1322个商品
⏰ 即将申请 0 个商品

==============📣系统通知📣==============
京东试用
京东账号1 #########
🎉 本次申请：0/0个商品🛒
🎉 0个商品待领取🤩
🎉 结束原因：申请完毕`

**Comment by shuye73** [comment]
一直有问题 没空修 先用小软件吧
