### ISSUE TITLE
大佬，每日签到好多失败，是黑号了还是没有活动了

### ISSUE THREAD

**Issue by dong0623** [shuye73/MyActions#36]
京东商城-直播: 失败, 原因: 未知 ⚠️
京东商城-闪购: 失败, 数据失联了，刷新看看吧~ ⚠️
京东商城-魔方: 失败, 原因: 无机会 ⚠️
京东商城-汽车: 失败, 原因: 活动暂未开始或者活动不存在 ⚠️
京东日历-翻牌: 失败, 活动太火爆了，请稍后再试~ ⚠️
京东商城-童装: 失败, 活动太火爆了，请稍后再试~ ⚠️
京东商城-母婴: 失败, 活动太火爆了，请稍后再试~ ⚠️
京东商城-数码: 失败, 活动太火爆了，请稍后再试~ ⚠️
京东商城-健康: 失败, 活动太火爆了，请稍后再试~ ⚠️
京东商城-个护: 失败, 活动太火爆了，请稍后再试~ ⚠️
京东商城-美妆: 失败, 活动太火爆了，请稍后再试~ ⚠️

**Comment by hacken156026692** [comment]
太火爆了，明显就是黑号。

**Comment by dong0623** [comment]
> 太火爆了，明显就是黑号。

话说黑号还能洗白吗？

**Comment by shuye73** [comment]
静置or销号
