### ISSUE TITLE
请教一下“被管理员封禁”的问题

### ISSUE THREAD

**Issue by V-Koo** [shuye73/MyActions#37]
今天凌晨收到邮件：“Actions jobs for this repository have been disabled by GitHub staff. If you are the repository owner, you can contact support via https://github.com/contact for more information.”
然后我把旧库删了，重新建了个新库，但是还是不能运行。
但我其他项目就是正常的。
请问大佬，我这种情况是github号被封了还是怎么搞的（是公开库，不是私有）

**Comment by shuye73** [comment]
封了，无解
