### ISSUE TITLE
我允许你私自上传我未开源的脚本了吗？

### ISSUE THREAD

**Issue by moposmall** [shuye73/MyActions#38]

**Comment by shuye73** [comment]
劳烦您指出来哪个是您未开源的，我上传的皆为网友提供。找出来我删除便是

**Comment by ICEOOX** [comment]
@shuye73 他也是fork的lx的代码啊，没看见有原创代码库， @moposmall 别是上这来秀的吧，你至少指出你的部分让大家查找

**Comment by moposmall** [comment]
> 劳烦您指出来哪个是您未开源的，我上传的皆为网友提供。找出来我删除便是

财富岛的提现脚本我有放到我的Github上吗？

**Comment by luoli8** [comment]
> > 劳烦您指出来哪个是您未开源的，我上传的皆为网友提供。找出来我删除便是
> 
> 财富岛的提现脚本我有放到我的Github上吗？

带着你的财富岛脚本去你自己的世界吧！！！千万别用中文和英文，你用哪个语言创作都不行，全世界的语言都是有版权的，因为语言不是你开发的，所以你一个字都不准用，自己开发一个语言，谁都看不懂，谁都抄不了（你写了个财富岛，我也写了个财富岛，咋着，感情财富岛这三字你买了版权啊）
