### ISSUE TITLE
大佬可以建个私人群，或者知识星球咩？ 付费的都可以。

### ISSUE THREAD

**Issue by lotusxhao** [shuye73/MyActions#4]
大佬可以建个私人群，或者知识星球咩？ 付费的都可以。 再来点JS的课程就完美了😄

**Comment by shuye73** [comment]
不会付费的，另外电报通知频道在想说的话中

**Comment by cisco6005** [comment]
电报群跳转不了，手机浏览器不行，还有什么方法能加电报群吗？安卓用的老王免费机场
