### ISSUE TITLE
助力码读取有错误

### ISSUE THREAD

**Issue by 1786178749** [shuye73/MyActions#40]
试了一下东东萌宠和种豆得豆的助力，都是读取东东农场的助力码，改掉配置文件里东东农场的助力码之后再运行那两个脚本，发现读取到的助力码也跟着变了，大佬有时间可以排查一下

**Comment by shuye73** [comment]
![image](https://user-images.githubusercontent.com/78575544/109326035-a2b08300-7891-11eb-841c-9ed732ef9e7f.png)
![image](https://user-images.githubusercontent.com/78575544/109326052-a80dcd80-7891-11eb-9a03-9e66f060e9b3.png)
![image](https://user-images.githubusercontent.com/78575544/109326078-afcd7200-7891-11eb-8e7d-6d870e6d359e.png)
![image](https://user-images.githubusercontent.com/78575544/109326531-46019800-7892-11eb-9cdc-9857ca510910.png)

建议自查，看了没有问题

**Comment by 1786178749** [comment]
自查了一遍，发现是我配置文件写错了
