### ISSUE TITLE
直播红包雨脚本运行出错

### ISSUE THREAD

**Issue by 09wqlin** [shuye73/MyActions#42]
直播红包雨运行脚本出错：
🔔超级直播间红包雨, 开始!
您的cookie选择的是用&隔开

====================共有6个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/2/26 下午11:31:01=====================

暂无红包雨
远程红包雨配置获取错误，从本地读取配置
无法从本地读取配置，请检查运行时间

🔔超级直播间红包雨, 结束! 🕛 0.811 秒

大佬，不知道是哪里出问题了，不知道是我个例还是其他人也会？能指导一下吗？谢谢

**Comment by shuye73** [comment]
看来失效了 马上删掉

**Comment by 09wqlin** [comment]
> 看来失效了 马上删掉

还有财富岛提现的脚本，进去日志显示需要京喜APP环境，不清楚是脚本的问题还是运行环境的问题
