### ISSUE TITLE
群晖里的docker shuye72镜像源更新问题

### ISSUE THREAD

**Issue by ICEOOX** [shuye73/MyActions#45]
我看到镜像源界面更新比较频繁，都是几小时之前更新
那么，我群晖用不用删除旧的容器并重新下载新的镜像？

目前镜像是244MMB

内页中
## Date: 2021-02-24
Date是指镜像的时间还是更新的时间？

同时感谢作者的代码分享!

**Comment by shuye73** [comment]
群晖好像自动更新镜像 应该不用你手动

**Comment by ICEOOX** [comment]
感谢作者辛苦维护脚本！

**Comment by ICEOOX** [comment]
> 群晖好像自动更新镜像 应该不用你手动

感谢作者辛苦维护脚本！
