### ISSUE TITLE
助力码获取失败

### ISSUE THREAD

**Issue by char98k** [shuye73/MyActions#51]
🔔获取互助码并格式化/docker自动更新容器下所有账号互助码, 开始!

====================共有1个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：3/2/2021, 10:34:25 AM=====================

{ [Error: ENOENT: no such file or directory, open '/home/runner/work/personal-JDHub/config/config.sh']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/runner/work/personal-JDHub/config/config.sh' }
执行完毕

您好，请帮忙看看这个是怎么回事，谢谢！

**Comment by shuye73** [comment]
报错为正常，但是报错也会获取到互助码
