### ISSUE TITLE
有个问题一直没弄明白，问别人也不告诉我，只好请教大佬

### ISSUE THREAD

**Issue by ICEOOX** [shuye73/MyActions#53]
在线编辑面板里编辑config.sh
里面有很多填写互助码的参数，这里的参数是填写别人的码还是自己的码？
我一直都没填写过，所以也没有人给我助力，也就是说config.sh应该填写自己的码，然后才会得到别人帮我助力的码？是不是应该玩的？
[https://i.loli.net/2021/03/02/4VGaTt6E7K195yo.png](https://i.loli.net/2021/03/02/4VGaTt6E7K195yo.png)

**Comment by shuye73** [comment]
填自己的给自己助力，填别人的给别人助力，填谁的给谁助力
