### ISSUE TITLE
最近好友助力都不成功

### ISSUE THREAD

**Issue by ronghuaxueleng** [shuye73/MyActions#55]
最近好友助力都不成功，比如种豆得豆、种水果之类的

**Comment by shuye73** [comment]
贴上问题截图

**Comment by ronghuaxueleng** [comment]
![微信图片_20210303113536](https://user-images.githubusercontent.com/9460517/109748904-9f602300-7c14-11eb-9148-84459d973f81.jpg)
![微信图片_20210303113544](https://user-images.githubusercontent.com/9460517/109748907-a129e680-7c14-11eb-802c-05c574b1b5d5.jpg)
从app看到的，以前肯定都有助力的

**Comment by shuye73** [comment]
你不贴上运行日志截图贴这个神仙也分析不出来你啥问题

**Comment by ronghuaxueleng** [comment]
日志没问题，我贴个屁，看到这个现象才说的，问题不是得你排查吗
