### ISSUE TITLE
这是啥问题呀~~

### ISSUE THREAD

**Issue by wesley1910** [shuye73/MyActions#57]
口袋书店 API请求失败，请检查网路重试
口袋书店 API请求失败，请检查网路重试
口袋书店 API请求失败，请检查网路重试
口袋书店 API请求失败，请检查网路重试
口袋书店 API请求失败，请检查网路重试
口袋书店 API请求失败，请检查网路重试
口袋书店 API请求失败，请检查网路重试
口袋书店 API请求失败，请检查网路重试
口袋书店 API请求失败，请检查网路重试
口袋书店 API请求失败，请检查网路重试
口袋书店 API请求失败，请检查网路重试

**Comment by wesley1910** [comment]
❌ 口袋书店, 失败! 原因: TypeError: Cannot read property 'storeGold' of undefined!

**Comment by shuye73** [comment]
部分接口失效 ，等作者更新
