### ISSUE TITLE
财富岛获取token问题

### ISSUE THREAD

**Issue by acoolbook** [shuye73/MyActions#58]
财富岛提现脚本要去京喜农场完成任务获取token
` 打开【❗️京喜农场❗️】，手动任意完成<工厂任务>、<签到任务>、<金牌厂长任务>一项，提示获取cookie成功即可，然后退出跑任务脚本
`
但是在京喜农场找不到这几个任务，求大佬指点

**Comment by shuye73** [comment]
领完种子就在下面有任务

**Comment by acoolbook** [comment]
> 领完种子就在下面

领完种子下边的任务中只有一个每日签到，也不知道是不是签到任务，手动做了没用，还是没token。
没有工厂任务，金牌厂长任务啊
