### ISSUE TITLE
最近购物车老是多一些莫名其妙的商品

### ISSUE THREAD

**Issue by hsh007** [shuye73/MyActions#60]
请问是因为上次token泄露造成的？（已经修改过密码了，旧token已经过期了的）
 还是因为活动自动添加的呢

**Comment by shuye73** [comment]
活动任务 建议停掉脚本观察

**Comment by luoli8** [comment]
大概是你的信息泄露了，这里给你个建议，关闭程序，别再使用了，很多人都这样，我跟你说的是真的！别不当回事，我替大家尝试尝试就好了，我不怕。千万别再用这种什么签到的东西了，根本不好用，你就当没有这么这一回事就好了，回归你自己的生活，也不用导出宣传这个程序，不要收藏更不要fork。

**Comment by luoli8** [comment]
> 请问是因为上次token泄露造成的？（已经修改过密码了，旧token已经过期了的）
> 还是因为活动自动添加的呢

一定要及时清除一切跟本脚本相关的东西，记住哦
