### ISSUE TITLE
豆子来源问题

### ISSUE THREAD

**Issue by simplein** [shuye73/MyActions#7]
大佬，我运行了两天，发现店铺关注领豆子，有些可能会没有去领。我原来手动点，是在“慢慢买”这个手机app上，每天会有人发布当日领豆子的链接集合，在店铺关注这个事情上，每天都会更新。能不能有些代码，能自动去“慢慢买”的贴子里面把链接抓过来，并自动运行。这个贴子标题一般是"2月6日 XX商城 X豆领取汇总"。这个贴子更新，每天都在排行榜前几位。

**Comment by shuye73** [comment]
店铺关注大多为时限性活动，github action有唤醒延迟，而且目前你说的爬虫我实现不了。综上所述这个可能不太会加入
