### ISSUE TITLE
JOY购买等级问题

### ISSUE THREAD

**Issue by lotusxhao** [shuye73/MyActions#8]
BUY_JOY_LEVEL这个参数好像没有在workflow里读取， 无法设置疯狂的JOY购买等级

**Comment by biubiu10086** [comment]
不用设置的，按照现在的逻辑会先生成8个34等级的joy放在下面生产金币，等金币到达可以买两个34级的之后，自动合成，上面4个自动合成的

**Comment by shuye73** [comment]
> 不用设置的，按照现在的逻辑会先生成8个34等级的joy放在下面生产金币，等金币到达可以买两个34级的之后，自动合成，上面4个自动合成的

正解

**Comment by lotusxhao** [comment]
但是这样默认购买30级JOY， 30级的价格就会越来越高，因为每购买一次，其售价都会增加。 如果设置BUY_JOY_LEVEL=29就可以购买29级，减少购买成本。

**Comment by shuye73** [comment]
目前这个逻辑已经非常不错了，如果作者有更新我会同步更新
